name: Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Upload Pre-built Packages
        run: |
          # The packages are pre-built and committed to the repository
          ls -la release-packages/
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-packages/QUIET-windows-x64.zip
            release-packages/QUIET-macOS.tar.gz
          body: |
            # QUIET v1.0.0 - AI-Powered Noise Cancellation
            
            Real-time background noise removal for desktop platforms.
            
            ## Downloads
            - **Windows**: `QUIET-windows-x64.zip`
            - **macOS**: `QUIET-macOS.tar.gz`
            
            ## Installation
            
            ### Windows
            1. Download and extract `QUIET-windows-x64.zip`
            2. Install [VB-Cable](https://vb-audio.com/Cable/) virtual audio driver
            3. Run `QUIET.exe`
            4. Configure input/output devices
            
            ### macOS
            1. Download and extract `QUIET-macOS.tar.gz`
            2. Install [BlackHole](https://github.com/ExistentialAudio/BlackHole) virtual audio driver
            3. Move `QUIET.app` to Applications folder
            4. Right-click and select "Open" (to bypass Gatekeeper on first run)
            5. Grant microphone permissions when prompted
            
            ## Features
            - Real-time noise reduction using RNNoise ML algorithm
            - Virtual audio device routing
            - Low latency (<30ms)
            - Cross-platform support
            
            ## Requirements
            - Windows 10+ or macOS 10.15+
            - 4GB RAM
            - Virtual audio driver (VB-Cable for Windows, BlackHole for macOS)
            
            ## Quick Start Guide
            
            ### Windows
            1. Set VB-Cable as default microphone in Windows
            2. Run QUIET.exe
            3. Select your physical microphone as input
            4. Select VB-Cable as output
            5. Enable noise cancellation
            
            ### macOS
            1. Create Multi-Output Device in Audio MIDI Setup
            2. Run QUIET.app
            3. Select your physical microphone as input
            4. Select BlackHole as output
            5. Enable noise cancellation
            
            ## Source Code
            https://github.com/jedarden/quiet
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}